# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
# Linux
- bash: |
    cd NormalMap
    make
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Linux' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/NormalMap'
    contents: 'libagsnormalmap.so'
    targetFolder: $(Build.ArtifactStagingDirectory)

# macOS
- bash: |
    cd NormalMap
    make
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: 'make'

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Darwin' )
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/NormalMap'
    contents: 'libagsnormalmap.dylib'
    targetFolder: $(Build.ArtifactStagingDirectory)

# Windows
- task: VSBuild@1
  condition: eq( variables['Agent.OS'], 'Windows_NT' )
  inputs:
    solution: 'NormalMap\vc2008\AGSNormalMap.sln' 
    platform: win32
    configuration: Release

- task: CopyFiles@2
  condition: eq( variables['Agent.OS'], 'Windows_NT' )   
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: '**/$(BuildConfiguration)/**/?(AGSNormalMap.dll)'
    targetFolder: $(Build.ArtifactStagingDirectory)

# Upload to Github Release
- task: GithubRelease@0 
  displayName: 'Create GitHub Release'  
  inputs:
    gitHubConnection: agsnormalmaps
    repositoryName: ericoporto/AGSNormalMap           
    assets: |
         $(Build.ArtifactStagingDirectory)/*.dll
         $(Build.ArtifactStagingDirectory)/*.so
         $(Build.ArtifactStagingDirectory)/*.dylib
    
